### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by AnotherStranger** [jaagr/xpp#9]
Hey,
i couldn't find a license file in this repo and i'm wondering which license applies to the code.

**Comment by patrick96** [comment]
Hi. Since there is no license attached to this repo, the code is not under any license and the original author retains the copyright to all of their work. This also means that we are not allowed to modify and redistribute the code and that technically this repo shouldn't be allowed to exist. I will open a PR and try to get everyone's consent to license the code in this repo under an open source license, so that we are in the clear.

**Comment by AnotherStranger** [comment]
Thanks. Once this is resolved i will attempt to get an ebuild for polybar into gentoo. :)
